
package com.sapint.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RfcReadTableWS", targetNamespace = "http://ws.sapint.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RfcReadTableWS {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "reset", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.Reset")
    @ResponseWrapper(localName = "resetResponse", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.ResetResponse")
    @Action(input = "http://ws.sapint.com/RfcReadTableWS/resetRequest", output = "http://ws.sapint.com/RfcReadTableWS/resetResponse")
    public void reset();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addField", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.AddField")
    @ResponseWrapper(localName = "addFieldResponse", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.AddFieldResponse")
    @Action(input = "http://ws.sapint.com/RfcReadTableWS/addFieldRequest", output = "http://ws.sapint.com/RfcReadTableWS/addFieldResponse")
    public void addField(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCriteria", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.AddCriteria")
    @ResponseWrapper(localName = "addCriteriaResponse", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.AddCriteriaResponse")
    @Action(input = "http://ws.sapint.com/RfcReadTableWS/addCriteriaRequest", output = "http://ws.sapint.com/RfcReadTableWS/addCriteriaResponse")
    public void addCriteria(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataTable", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.GetDataTable")
    @ResponseWrapper(localName = "getDataTableResponse", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.GetDataTableResponse")
    @Action(input = "http://ws.sapint.com/RfcReadTableWS/getDataTableRequest", output = "http://ws.sapint.com/RfcReadTableWS/getDataTableResponse")
    public String getDataTable(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
