
package com.sapint.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RfcReadTableWSService", targetNamespace = "http://ws.sapint.com/", wsdlLocation = "http://localhost:8888/sapint/RFCReadTable?wsdl")
public class RfcReadTableWSService
    extends Service
{

    private final static URL RFCREADTABLEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException RFCREADTABLEWSSERVICE_EXCEPTION;
    private final static QName RFCREADTABLEWSSERVICE_QNAME = new QName("http://ws.sapint.com/", "RfcReadTableWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/sapint/RFCReadTable?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RFCREADTABLEWSSERVICE_WSDL_LOCATION = url;
        RFCREADTABLEWSSERVICE_EXCEPTION = e;
    }

    public RfcReadTableWSService() {
        super(__getWsdlLocation(), RFCREADTABLEWSSERVICE_QNAME);
    }

    public RfcReadTableWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RFCREADTABLEWSSERVICE_QNAME, features);
    }

    public RfcReadTableWSService(URL wsdlLocation) {
        super(wsdlLocation, RFCREADTABLEWSSERVICE_QNAME);
    }

    public RfcReadTableWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RFCREADTABLEWSSERVICE_QNAME, features);
    }

    public RfcReadTableWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RfcReadTableWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RfcReadTableWS
     */
    @WebEndpoint(name = "RfcReadTableWSPort")
    public RfcReadTableWS getRfcReadTableWSPort() {
        return super.getPort(new QName("http://ws.sapint.com/", "RfcReadTableWSPort"), RfcReadTableWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RfcReadTableWS
     */
    @WebEndpoint(name = "RfcReadTableWSPort")
    public RfcReadTableWS getRfcReadTableWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sapint.com/", "RfcReadTableWSPort"), RfcReadTableWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RFCREADTABLEWSSERVICE_EXCEPTION!= null) {
            throw RFCREADTABLEWSSERVICE_EXCEPTION;
        }
        return RFCREADTABLEWSSERVICE_WSDL_LOCATION;
    }

}
