
package com.sapint.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RfcWSService", targetNamespace = "http://ws.sapint.com/", wsdlLocation = "http://localhost:8888/sapint/getRFCFunctionLIst?wsdl")
public class RfcWSService
    extends Service
{

    private final static URL RFCWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException RFCWSSERVICE_EXCEPTION;
    private final static QName RFCWSSERVICE_QNAME = new QName("http://ws.sapint.com/", "RfcWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/sapint/getRFCFunctionLIst?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RFCWSSERVICE_WSDL_LOCATION = url;
        RFCWSSERVICE_EXCEPTION = e;
    }

    public RfcWSService() {
        super(__getWsdlLocation(), RFCWSSERVICE_QNAME);
    }

    public RfcWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RFCWSSERVICE_QNAME, features);
    }

    public RfcWSService(URL wsdlLocation) {
        super(wsdlLocation, RFCWSSERVICE_QNAME);
    }

    public RfcWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RFCWSSERVICE_QNAME, features);
    }

    public RfcWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RfcWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RfcWS
     */
    @WebEndpoint(name = "RfcWSPort")
    public RfcWS getRfcWSPort() {
        return super.getPort(new QName("http://ws.sapint.com/", "RfcWSPort"), RfcWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RfcWS
     */
    @WebEndpoint(name = "RfcWSPort")
    public RfcWS getRfcWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sapint.com/", "RfcWSPort"), RfcWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RFCWSSERVICE_EXCEPTION!= null) {
            throw RFCWSSERVICE_EXCEPTION;
        }
        return RFCWSSERVICE_WSDL_LOCATION;
    }

}
