
package com.sapint.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RfcWS", targetNamespace = "http://ws.sapint.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RfcWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRFCFunctionLIst", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.GetRFCFunctionLIst")
    @ResponseWrapper(localName = "getRFCFunctionLIstResponse", targetNamespace = "http://ws.sapint.com/", className = "com.sapint.wsclient.GetRFCFunctionLIstResponse")
    @Action(input = "http://ws.sapint.com/RfcWS/getRFCFunctionLIstRequest", output = "http://ws.sapint.com/RfcWS/getRFCFunctionLIstResponse")
    public String getRFCFunctionLIst(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
